#include $(srctree)/drivers/misc/mediatek/Makefile.custom
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/AH1887

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/AH1887/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
obj-y := ah1887.o
